services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # As in the "app" service, use "forwardPorts" in **devcontainer.json** to forward an app port locally.